version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
    nodejs: "16"
  apt_packages:
    - build-essential
    - cmake
    - fonts-noto-color-emoji  # For better-looking icons.
    - g++

sphinx:
  configuration: doc/source/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: doc/source/requirements.txt

formats:
  - pdf
  - epub

# vim: set sts=2 sw=2:
